### ISSUE TITLE
missing semicolon after "export PATH={{ os_path }}"

### ISSUE THREAD

**Issue by dwayneam** [redhat-cop/infra.leapp#180]
I assume "infra.leapp.analysis : Leapp preupgrade report" changed from a "ansible.builtin.shell: |" to "ansible.builtin.shell: >" recently and you forgot to add a semicolon after the "export PATH={{ os_path }}".  This worked fine last week and broke for me today (or over the weekend)

Bug fix:
File: ~/.ansible/collections/ansible_collections/infra/leapp/roles/analysis/tasks/analysis-leapp.yml
Task: Leapp preupgrade report
Change:
    export PATH={{ os_path }}
    set -o pipefail;
To:
    export PATH={{ os_path }};
    set -o pipefail;

PS: Doesn't hurt to add a semicolon after ALL "export PATH={{ os_path }}"

**Comment by djdanielsson** [comment]
so I just looked at the code, https://github.com/redhat-cop/infra.leapp/blob/0a392839f0bf3df514f7d5e89aaaf77fa5ad8a22/roles/analysis/tasks/analysis-leapp.yml#L70 has the ; and I checked this task has not changed for 2 months, I have a feeling this issue is related to a specific release, can you give me the exact version showing from: `ansible-galaxy collection list` that might help solve this.
