### ISSUE TITLE
Validated Ansible Content Collection on Red Hat automation hub appears to require community.general

### ISSUE THREAD

**Issue by bonnevil** [redhat-cop/infra.leapp#221]
The 1.3.1 version of **infra.leapp** published at https://console.redhat.com/ansible/automation-hub/repo/validated/infra/leapp/dependencies/ as a validated Ansible Content Collection appears to claim that it has no dependencies, but we're seeing failures because the unsupported **community.general** Ansible Content Collection is not present but is used by code in the collection.  (Specifically, at least the community.general.redhat_subscription module, which as I understand it was not written by Red Hat and that its use is apparently discouraged by internal engineering.)

I can't open an issue directly with Red Hat on this item because my relevant employee account does not have bug filing access right now through some misconfiguration.

**Comment by djdanielsson** [comment]
we cannot put it in the meta data to auto pull because community.general doesn't exist in the validated repo and it will fail to find it. it does look like we do not note that in the main readme about requiring that. we may want to re-look at using system roles and have the validated collection version use RHEL version over Fedora...

**Comment by swapdisk** [comment]
Fixed with #222.
